hassio-addons/addon-traccar

- .gitlab-ci.yml
- traccar/Dockerfile
- traccar/build.json
Upgrades the base image and packages
Might fix #21, untested
> Upgrade base images and packages

- traccar/.README.j2
Adds link to Traccar website to match README.md.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
> :books: Adds link to Traccar website

- README.md
- traccar/.README.j2
Small documentation improvements (in part thanks to Grammarly), change "component" to "integration" and typo fix.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
> :books: Small documentation improvements

- traccar/Dockerfile
Update traccar to 4.7
https://github.com/traccar/traccar/releases/tag/v4.7
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
<blockquote><img src="https://avatars2.githubusercontent.com/u/37892282?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/traccar/traccar">traccar/traccar</a></strong></div><div>Traccar GPS Tracking System. Contribute to traccar/traccar development by creating an account on GitHub.</div></blockquote>
> :arrow_up: Upgrades Traccar to 4.7

- LICENSE.md
- README.md
- traccar/.README.j2
- traccar/DOCS.md
> Happy New Year

- traccar/Dockerfile
- traccar/build.json
Upgrades the add-on base image
> Upgrade add-on base image to 9.1.0

- traccar/Dockerfile
- traccar/build.json
> Upgrade add-on base image to 9.1.1

- traccar/Dockerfile
- traccar/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2
> Upgrade add-on base image to 9.1.2

- traccar/Dockerfile
Upgrades openjdk8-jre to 8.275.01-r0
> :arrow_up: Upgrades openjdk8-jre to 8.275.01-r0

- README.md
> Basic name change Hass.io -> Home Assistant

- traccar/Dockerfile
> ⬆️ Upgrades nss to 3.63-r0

- traccar/Dockerfile
- traccar/build.json
Upgrades add-on base image to v9.1.7
> ⬆️ Upgrades add-on base image to v9.1.7

- traccar/Dockerfile
- traccar/build.json
Upgrades add-on base image to v9.2.0
> Upgrades add-on base image to v9.2.0

- traccar/Dockerfile
Upgrades mariadb-client to 10.5.9-r0
> ⬆️ Upgrades mariadb-client to 10.5.9-r0

- traccar/Dockerfile
- traccar/build.json
Upgrades add-on base image to v9.2.1
> ⬆️ Upgrades add-on base image to v9.2.1

- traccar/Dockerfile
> ⬆️ Upgrades nginx to 1.18.0-r15

- traccar/Dockerfile
> ⬆️ Upgrades nss to 3.66-r0

- traccar/Dockerfile
https://www.traccar.org/blog/traccar-4-13/
> ⬆️ Upgrades Traccar to v4.13

- traccar/Dockerfile
- traccar/build.json
Upgrades add-on base image to v10.0.0
> ⬆️ Upgrades add-on base image to v10.0.0

- traccar/Dockerfile
Upgrades mariadb-client to 10.5.11-r0
> ⬆️ Upgrades mariadb-client to 10.5.11-r0

- traccar/Dockerfile
> ⬆️ Upgrade to openjdk11

- traccar/Dockerfile
Upgrades mariadb-client to 10.5.12-r0
> ⬆️ Upgrades mariadb-client to 10.5.12-r0

- traccar/config.json
> 🏎 Enable streaming mode for Ingress

- traccar/Dockerfile
- traccar/build.json
Upgrades add-on base image to v10.0.1
> ⬆️ Upgrades add-on base image to v10.0.1

- traccar/Dockerfile
- traccar/build.json
Upgrades add-on base image to 10.1.0
> ⬆️ Upgrades add-on base image to 10.1.0

- traccar/rootfs/etc/traccar/hassio.xml
Fixes a bug whereby the event selection query is now incorrect. Details as per issue #132 
* Report events using wrong query #132
> :bug: Fix events selection query

- traccar/Dockerfile
https://github.com/traccar/traccar/releases/tag/v4.14
> ⬆️ Upgrades Traccar to v4.14

- traccar/Dockerfile
- traccar/build.yaml
Upgrades add-on base image to 10.2.1
> ⬆️ Upgrades add-on base image to 10.2.1

- traccar/Dockerfile
- traccar/build.yaml
Upgrades add-on base image to 10.2.2
> ⬆️ Upgrades add-on base image to 10.2.2

- traccar/Dockerfile
- traccar/build.yaml
Upgrades add-on base image to 11.0.0
> ⬆️ Upgrades add-on base image to 11.0.0

- LICENSE.md
- README.md
- traccar/.README.j2
- traccar/DOCS.md
> :fireworks: Updates maintenance/license year to 2022

- traccar/Dockerfile
> ⬆️ Upgrades nss to 3.72.1-r0

- traccar/Dockerfile
- traccar/build.yaml
Upgrades add-on base image to 11.0.1
> ⬆️ Upgrades add-on base image to 11.0.1

- traccar/Dockerfile
Upgrades mariadb-client to 10.6.7-r0
> ⬆️ Upgrades mariadb-client to 10.6.7-r0

- traccar/Dockerfile
- traccar/build.yaml
Upgrades add-on base image to 11.1.0
> ⬆️ Upgrades add-on base image to 11.1.0

- .github/workflows/deploy.yaml
- traccar/build.yaml
- traccar/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

- traccar/DOCS.md
Add My buttons to documentation
> :books: Add My buttons to documentation

- traccar/Dockerfile
Upgrades mariadb-client to 10.6.8-r0
> ⬆️ Upgrades mariadb-client to 10.6.8-r0

- traccar/Dockerfile
> ⬆️ Upgrades nginx to 1.20.2-r1

- traccar/Dockerfile
> ⬆️ Upgrades nss to 3.76.1-r0

- traccar/DOCS.md
One My Home Assistant button to handle both the add-on and repository
> :books: Use new My Home Assistant link format

- traccar/Dockerfile
- traccar/build.yaml
Upgrades add-on base image to 11.1.2
> ⬆️ Upgrades add-on base image to 11.1.2

- traccar/Dockerfile
- traccar/build.yaml
- traccar/rootfs/etc/cont-init.d/mysql.sh
- traccar/rootfs/etc/cont-init.d/nginx.sh
- traccar/rootfs/etc/cont-init.d/traccar.sh
- traccar/rootfs/etc/services.d/nginx/finish
- traccar/rootfs/etc/services.d/nginx/run
- traccar/rootfs/etc/services.d/traccar/finish
- traccar/rootfs/etc/services.d/traccar/run
Upgrades add-on base image to 12.0.0
> ⬆️ Upgrades add-on base image to 12.0.0

- traccar/config.yaml
> :ambulance: Fix web UI entry point

- traccar/Dockerfile
- traccar/build.yaml
> ⬆️ Upgrades add-on base image to 12.2.4

- LICENSE.md
- README.md
- traccar/.README.j2
- traccar/DOCS.md
> :fireworks: Updates maintenance/license year to 2023

- .github/dependabot.yaml
- .github/renovate.json
- traccar/Dockerfile
> Add Renovate for dependency management

- traccar/rootfs/etc/traccar/hassio.xml
> Sync default config with Traccar project

- traccar/DOCS.md
It now asks to register an account (and thus no longer set up an default account).
> :books: Adjust documentation for new Traccar account set up

- traccar/DOCS.md
> (Describe the changes and rationale behind them)
Fixes a broken URL in the documentation.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
> Fix broken URL

- LICENSE.md
- README.md
- traccar/.README.j2
- traccar/DOCS.md
> :fireworks: Updates maintenance/license year to 2024
